#!/usr/bin/env python
# coding=utf-8
# Created by @andrians58 @ 2024/2/29
import os


def adjust_filepath(filepath: str):
    if filepath.startswith("~"):
        filepath = os.path.expanduser(filepath)
    return filepath
